### PR TITLE
Better image pasting

### PR DESCRIPTION
**Pull request by TGRHavoc**
Added a "Upload Image" button to the editor to allow users to upload images from their local system rather than having to paste images into a text box  (#16)

Whilst uploading fairly large images (1MB-3MB in size) I haven't come across any issues.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I, personally, don't like uploading images... The normal use case is that people crop something onto the clipboard. I have never had the case that I had an image _file_ I wanted to include. I don't oppose also allowing file upload, but pasting is the more common use case. I agree, the way it was implemented was wrong/cumbersome. So, it's on the list to allow better pasting (e.g. actually pasting into the image, rather than a text input field. But replacing it with upload is in my view a regression. Opinions?

**Comment by TGRHavoc** [comment]
Ah, sorry I didn't realize you wanted the user to have the image on clipboard.

Now that I understand the way in which you want the user to upload their images, I agree pasting the image into the image's preview location would be better than pasting to a text box.

**Comment by marc-hanheide** [comment]
Yeah, sorry, I much appreciated the contribution, so keeping upload as an option is good! But pasting should also work, I'd say.

**Comment by TGRHavoc** [comment]
@marc-hanheide Sorry I haven't been active, not had much spare time.

Anyhow, I've implemented the pasting of images on the user's clipboard.

**Comment by marc-hanheide** [comment]
Thanks... I just tested it on Chrome, and while the storage works when using the upload button, the image is not stored when pasted. I didn't investigate yet why this might be the case. To reproduce, simply paste an image in chrome and hit "save".

**Comment by marc-hanheide** [comment]
Ah, you may have fixed it already...

**Comment by marc-hanheide** [comment]
yeah, you did! Cool, many thanks, works now.

**Pull request merged**
