### PR TITLE
Python 3.5 update

### PR DESCRIPTION
**Pull request by TGRHavoc**
I had some spare time this week and thought I'd try and update the app to Python 3.5 so, that's what this PR attempts 😛 

To install the latest version (still in development but, seems to work) of web.py, I followed some  instructions off of [StackOverflow ](http://stackoverflow.com/a/41306820). The other packages were just installed normally.

If you want a full break-down of the environment:
Python: 3.5.2
pip: 8.1.1
web.py: 0.40.dev0
pymongo: 3.4.0
httpagentparser: 1.7.8
Mongo: 3.2.9

### CODE REVIEW

**Comment by marc-hanheide** [comment]
cool stuff. Would this still work with Python 2.7.x or is 3.5 needed. How about any lower Python 3.x version? 

I think for now, I'd leave this PR open and not merge it, as I'd have to update the production environment first.

**Comment by TGRHavoc** [comment]
> Would this still work with Python 2.7.x or is 3.5 needed

As far as I'm aware, any Python version < 3.0.x won't work because of the changes between the two versions 😢 (mainly "urlparse" moved to "urllib.parse").

> How about any lower Python 3.x version
 
I could only go as low as 3.2 on my machine however, with the latest web.py package (0.40.dev0) it seems to work (it compiles and starts with no errors).

**Comment by TGRHavoc** [comment]
Hmm... After some research (more specifically, StackOverflow). I've found a way to make the [app backwards-compatible](http://stackoverflow.com/a/1532531).... It should work with Python 2.7.x and Python 3.x..

I haven't properly tested it yet but, it compiles and runs without any errors (using web.py 0.40.dev0).

**Comment by marc-hanheide** [comment]
cool... I'll test at some point.

**Pull request closed without merging**
